version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Downloading out.txt from S3..."
      - curl -o out.txt https://codepipeline-ap-south-1-402428956422.s3.ap-south-1.amazonaws.com/outart/out.txt
      - export CONTENT=$(cat out.txt)
      - echo "Content of out.txt: $CONTENT"
      - |
        if [ "$CONTENT" == "backend" ]; then
          echo Updating apt-get
          apt-get update
          echo Installing Maven
          apt-get install -y maven
        else
          echo "No backend update detected. Exiting..."
          exit 0
        fi

  pre_build:
    commands:
      - echo Pre-build phase started on date
      - mvn --version

  build:
    commands:
      - echo Build started on date
      - echo Building the Maven project...
      - mvn clean install

  post_build:
    commands:
      - echo Post-build phase started on date
      - echo test comment

artifacts:
  files:
    - target/*.war
  discard-paths: yes
